# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/anshpatel/PycharmProjects/TaxiLuggageTracker/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from core import *
from core.cargo import Trunk
from core.traveller import Traveller


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 795)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("#centralwidget{\n"
                                 "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.044335 "
                                 "rgba(39, 52, 114, 255), stop:0.876847 rgba(123, 9, 154, 255));\n "
                                 " }\n")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 500))
        self.centralwidget.setStyleSheet("border: 0px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(969, 472))
        self.frame_3.setMaximumSize(QtCore.QSize(969, 472))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_map = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_map.sizePolicy().hasHeightForWidth())
        self.frame_map.setSizePolicy(sizePolicy)
        self.frame_map.setMaximumSize(QtCore.QSize(480, 476))
        self.frame_map.setStatusTip("")
        self.frame_map.setAutoFillBackground(False)
        self.frame_map.setStyleSheet("#frame_map{\n"
                                     "background-image: url(:/path/map_path.png);\n"
                                     "background-repeat: no-repeat;\n"
                                     "background-position: left;\n"
                                     "}\n")
        self.frame_map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_map.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_map.setObjectName("frame_map")
        self.btn_dest_a = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_a.setGeometry(QtCore.QRect(30, 90, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_a.setFont(font)
        self.btn_dest_a.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_a.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgb(161, 255, 138);\n")
        self.btn_dest_a.setObjectName("btn_dest_a")
        self.btn_dest_c = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_c.setGeometry(QtCore.QRect(30, 250, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_c.setFont(font)
        self.btn_dest_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_c.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgb(161, 255, 138);\n")
        self.btn_dest_c.setObjectName("btn_dest_c")
        self.btn_dest_b = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_b.setGeometry(QtCore.QRect(350, 150, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_b.setFont(font)
        self.btn_dest_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_b.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgb(161, 255, 138);\n")
        self.btn_dest_b.setObjectName("btn_dest_b")
        self.btn_dest_e = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_e.setGeometry(QtCore.QRect(30, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_e.setFont(font)
        self.btn_dest_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_e.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgb(161, 255, 138);\n")
        self.btn_dest_e.setObjectName("btn_dest_e")
        self.btn_dest_d = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_d.setGeometry(QtCore.QRect(340, 340, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_d.setFont(font)
        self.btn_dest_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_d.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgb(161, 255, 138);\n")
        self.btn_dest_d.setObjectName("btn_dest_d")
        self.horizontalLayout_2.addWidget(self.frame_map)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_entry = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_entry.sizePolicy().hasHeightForWidth())
        self.name_entry.setSizePolicy(sizePolicy)
        self.name_entry.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.name_entry.setFont(font)
        self.name_entry.setStyleSheet("border-radius:15px;\n"
                                      "background-color: rgba(0, 0, 0, 70);\n")
        self.name_entry.setObjectName("name_entry")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_entry)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.contact_entry = QtWidgets.QLineEdit(self.frame_2)
        self.contact_entry.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.contact_entry.setFont(font)
        self.contact_entry.setStyleSheet("border-radius:15px;\n"
                                         "background-color: rgba(0, 0, 0, 70);\n")
        self.contact_entry.setObjectName("contact_entry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contact_entry)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.weight_entry = QtWidgets.QLineEdit(self.frame_2)
        self.weight_entry.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.weight_entry.setFont(font)
        self.weight_entry.setStyleSheet("border-radius:15px;\n"
                                        "background-color: rgba(0, 0, 0, 70);\n")
        self.weight_entry.setObjectName("weight_entry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weight_entry)
        self.add_weight_frag = QtWidgets.QPushButton(self.frame_2)
        self.add_weight_frag.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.add_weight_frag.setFont(font)
        self.add_weight_frag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_weight_frag.setStyleSheet("border-radius:15px;\n"
                                           "background-color: rgba(87, 252, 0, 200);\n"
                                           "color:rgb(255, 255, 255);\n")
        self.add_weight_frag.setObjectName("add_weight_frag")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_weight_frag)
        self.rem_weight_frag = QtWidgets.QPushButton(self.frame_2)
        self.rem_weight_frag.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rem_weight_frag.setFont(font)
        self.rem_weight_frag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rem_weight_frag.setStyleSheet("border-radius:15px;\n"
                                           "background-color: rgb(252, 0, 87);\n"
                                           "color:rgb(255, 255, 255);\n")
        self.rem_weight_frag.setObjectName("rem_weight_frag")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rem_weight_frag)
        self.make_entry_btn = QtWidgets.QPushButton(self.frame_2)
        self.make_entry_btn.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.make_entry_btn.setFont(font)
        self.make_entry_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.make_entry_btn.setStyleSheet("border-radius:15px;\n"
                                          "background-color: rgba(87, 252, 0, 200);\n"
                                          "color:rgb(255, 255, 255);\n")
        self.make_entry_btn.setObjectName("make_entry_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.make_entry_btn)
        self.make_exit_btn = QtWidgets.QPushButton(self.frame_2)
        self.make_exit_btn.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.make_exit_btn.setFont(font)
        self.make_exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.make_exit_btn.setStyleSheet("border-radius:15px;\n"
                                         "background-color: rgb(252, 0, 87);\n"
                                         "color:rgb(255, 255, 255);\n")
        self.make_exit_btn.setObjectName("make_exit_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.make_exit_btn)
        self.entry_pass_label = QtWidgets.QLabel(self.frame_2)
        self.entry_pass_label.setMinimumSize(QtCore.QSize(324, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.entry_pass_label.setFont(font)
        self.entry_pass_label.setStyleSheet("color: rgb(0, 255, 0);")
        self.entry_pass_label.setObjectName("entry_pass_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.entry_pass_label)
        self.exit_pass_label = QtWidgets.QLabel(self.frame_2)
        self.exit_pass_label.setMinimumSize(QtCore.QSize(324, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.exit_pass_label.setFont(font)
        self.exit_pass_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.exit_pass_label.setObjectName("exit_pass_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.exit_pass_label)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setStyleSheet("COLOR:rgb(255, 255, 255)")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 29, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.traveller_combobox = QtWidgets.QComboBox(self.groupBox)
        self.traveller_combobox.setMinimumSize(QtCore.QSize(0, 30))
        self.traveller_combobox.setStyleSheet("background-color: rgba(0, 0, 0, 57);\n"
                                              "border-radius: 15px;\n"
                                              "color: rgb(255, 255, 255);\n")
        self.traveller_combobox.setObjectName("traveller_combobox")
        self.verticalLayout_2.addWidget(self.traveller_combobox)
        self.description_area = QtWidgets.QPlainTextEdit(self.groupBox)
        self.description_area.setStyleSheet("color: rgba(255, 255, 255, 227);\n"
                                            "background-color: rgba(0, 0, 0, 140);\n"
                                            "border-radius: 15px;\n")
        self.description_area.setMidLineWidth(0)
        self.description_area.setUndoRedoEnabled(True)
        self.description_area.setReadOnly(True)
        self.description_area.setObjectName("description_area")
        self.verticalLayout_2.addWidget(self.description_area)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # TODO: Below are custom event handler statements and global variables

        self.cargo = Trunk(0)

        self.make_entry_btn.clicked.connect(
            lambda: self.generate_traveller_entity(
                self.name_entry.text(),
                self.contact_entry.text(),
                self.luggage_handler_temp,
            )
        )

        self.add_weight_frag.clicked.connect(
            lambda: self.pos_spike_handler(
                self.weight_entry.text(),
            )
        )



        self.btn_dest_a.clicked.connect(
            lambda: self.processRemovedWeight(),
        )

        self.btn_dest_b.clicked.connect(
            lambda: self.processRemovedWeight(),
        )

        self.btn_dest_c.clicked.connect(
            lambda: self.processRemovedWeight(),
        )

        self.btn_dest_d.clicked.connect(
            lambda: self.processRemovedWeight(),
        )

        self.btn_dest_e.clicked.connect(
            lambda: self.processRemovedWeight(),
        )



        self.btn_dest_a.clicked.connect(
            lambda: self.onMoveToDestA(),
        )

        self.btn_dest_b.clicked.connect(
            lambda: self.onMoveToDestB(),
        )

        self.btn_dest_c.clicked.connect(
            lambda: self.onMoveToDestC(),
        )

        self.btn_dest_d.clicked.connect(
            lambda: self.onMoveToDestD(),
        )

        self.btn_dest_e.clicked.connect(
            lambda: self.onMoveToDestE(),
        )

        self.entry_pass_label.hide()
        self.exit_pass_label.hide()
        self.make_exit_btn.hide()
        self.populateTravellerCombobox()



        self.luggage_handler_temp = []
        self.latest_traveller = 0
        self.travellers = []
        self.sub_neg_weight_spikes = []

    def processRemovedWeight(self):
        if self.sub_neg_weight_spikes is not []:
            self.cargo.remove_luggage(self.sub_neg_weight_spikes)
            self.sub_neg_weight_spikes = []

    def pos_spike_handler(self, ws):
        self.luggage_handler_temp.append(int(ws))
        self.weight_entry.clear()

    def generate_traveller_entity(self, name, contact, weight_spikes):
        self.travellers.append(Traveller(weight_spikes, name, contact))

    def onNewTraveller(self):
        # TODO: visual interface for new entered traveller
        pass

    def onTravellerExit(self):
        # TODO: visual interface for last exited traveller
        pass

    def populateTravellerCombobox(self):
        # TODO: fetch list of all traveller since the start and display
        pass

    def onMoveToDestA(self):
        pass

    def onMoveToDestB(self):
        pass

    def onMoveToDestC(self):
        pass

    def onMoveToDestD(self):
        pass

    def onMoveToDestE(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dest_a.setWhatsThis(_translate("MainWindow",
                                                "<html><head/><body><p>Theater</p><p>Interact with Destination A</p></body></html>"))
        self.btn_dest_a.setText(_translate("MainWindow", "A"))
        self.btn_dest_c.setText(_translate("MainWindow", "C"))
        self.btn_dest_b.setText(_translate("MainWindow", "B"))
        self.btn_dest_e.setText(_translate("MainWindow", "E"))
        self.btn_dest_d.setText(_translate("MainWindow", "D"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Contact:"))
        self.label_3.setText(_translate("MainWindow", "Weight(s):"))
        self.add_weight_frag.setText(_translate("MainWindow", "+"))
        self.rem_weight_frag.setText(_translate("MainWindow", "-"))
        self.make_entry_btn.setText(_translate("MainWindow", "ENTRY"))
        self.make_exit_btn.setText(_translate("MainWindow", "EXIT"))
        self.entry_pass_label.setText(_translate("MainWindow", "TextLabel"))
        self.exit_pass_label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "TRACKER"))


import res_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
