# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/anshpatel/PycharmProjects/TaxiLuggageTracker/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 795)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("#centralwidget{\n"
                                 "                background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.044335 rgba(39, 52, 114,\n"
                                 "                255), stop:0.876847 rgba(123, 9, 154, 255));\n"
                                 "                }\n"
                                 "            ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 500))
        self.centralwidget.setStyleSheet("border: 0px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(969, 472))
        self.frame_3.setMaximumSize(QtCore.QSize(969, 472))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_map = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_map.sizePolicy().hasHeightForWidth())
        self.frame_map.setSizePolicy(sizePolicy)
        self.frame_map.setMaximumSize(QtCore.QSize(480, 476))
        self.frame_map.setStatusTip("")
        self.frame_map.setAutoFillBackground(False)
        self.frame_map.setStyleSheet("#frame_map{\n"
                                     "                                            background-image: url(:/path/map_path.png);\n"
                                     "                                            background-repeat: no-repeat;\n"
                                     "                                            background-position: left;\n"
                                     "                                            }\n"
                                     "                                        ")
        self.frame_map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_map.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_map.setObjectName("frame_map")
        self.btn_dest_a = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_a.setGeometry(QtCore.QRect(30, 90, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_a.setFont(font)
        self.btn_dest_a.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_a.setStyleSheet("border-radius:15px;\n"
                                      "                                                background-color: rgb(161, 255, 138);\n"
                                      "                                            ")
        self.btn_dest_a.setObjectName("btn_dest_a")
        self.btn_dest_c = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_c.setGeometry(QtCore.QRect(30, 250, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_c.setFont(font)
        self.btn_dest_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_c.setStyleSheet("border-radius:15px;\n"
                                      "                                                background-color: rgb(161, 255, 138);\n"
                                      "                                            ")
        self.btn_dest_c.setObjectName("btn_dest_c")
        self.btn_dest_b = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_b.setGeometry(QtCore.QRect(350, 150, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_b.setFont(font)
        self.btn_dest_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_b.setStyleSheet("border-radius:15px;\n"
                                      "                                                background-color: rgb(161, 255, 138);\n"
                                      "                                            ")
        self.btn_dest_b.setObjectName("btn_dest_b")
        self.btn_dest_e = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_e.setGeometry(QtCore.QRect(30, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_e.setFont(font)
        self.btn_dest_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_e.setStyleSheet("border-radius:15px;\n"
                                      "                                                background-color: rgb(161, 255, 138);\n"
                                      "                                            ")
        self.btn_dest_e.setObjectName("btn_dest_e")
        self.btn_dest_d = QtWidgets.QPushButton(self.frame_map)
        self.btn_dest_d.setGeometry(QtCore.QRect(340, 340, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_d.setFont(font)
        self.btn_dest_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_d.setStyleSheet("border-radius:15px;\n"
                                      "                                                background-color: rgb(161, 255, 138);\n"
                                      "                                            ")
        self.btn_dest_d.setObjectName("btn_dest_d")
        self.horizontalLayout_2.addWidget(self.frame_map)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:15px;\n"
                                    "                                                        background-color: rgba(0, 0, 0, 70);\n"
                                    "                                                    ")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius:15px;\n"
                                      "                                                        background-color: rgba(0, 0, 0, 70);\n"
                                      "                                                    ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius:15px;\n"
                                      "                                                        background-color: rgba(0, 0, 0, 70);\n"
                                      "                                                    ")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.btn_dest_a_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn_dest_a_2.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_a_2.setFont(font)
        self.btn_dest_a_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_a_2.setStyleSheet("border-radius:15px;\n"
                                        "                                                        background-color: rgba(87, 252, 0, 200);\n"
                                        "                                                        color:rgb(255, 255, 255);\n"
                                        "                                                    ")
        self.btn_dest_a_2.setObjectName("btn_dest_a_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_dest_a_2)
        self.btn_dest_a_3 = QtWidgets.QPushButton(self.frame_2)
        self.btn_dest_a_3.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_dest_a_3.setFont(font)
        self.btn_dest_a_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dest_a_3.setStyleSheet("border-radius:15px;\n"
                                        "                                                        background-color: rgb(252, 0, 87);\n"
                                        "                                                        color:rgb(255, 255, 255);\n"
                                        "                                                    ")
        self.btn_dest_a_3.setObjectName("btn_dest_a_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_dest_a_3)
        self.make_entry_btn = QtWidgets.QPushButton(self.frame_2)
        self.make_entry_btn.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.make_entry_btn.setFont(font)
        self.make_entry_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.make_entry_btn.setStyleSheet("border-radius:15px;\n"
                                          "                                                        background-color: rgba(87, 252, 0, 200);\n"
                                          "                                                        color:rgb(255, 255, 255);\n"
                                          "                                                    ")
        self.make_entry_btn.setObjectName("make_entry_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.make_entry_btn)
        self.make_exit_btn = QtWidgets.QPushButton(self.frame_2)
        self.make_exit_btn.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.make_exit_btn.setFont(font)
        self.make_exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.make_exit_btn.setStyleSheet("border-radius:15px;\n"
                                         "                                                        background-color: rgb(252, 0, 87);\n"
                                         "                                                        color:rgb(255, 255, 255);\n"
                                         "                                                    ")
        self.make_exit_btn.setObjectName("make_exit_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.make_exit_btn)
        self.entry_pass_label = QtWidgets.QLabel(self.frame_2)
        self.entry_pass_label.setMinimumSize(QtCore.QSize(324, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.entry_pass_label.setFont(font)
        self.entry_pass_label.setStyleSheet("color: rgb(0, 255, 0);")
        self.entry_pass_label.setObjectName("entry_pass_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.entry_pass_label)
        self.exit_pass_label_2 = QtWidgets.QLabel(self.frame_2)
        self.exit_pass_label_2.setMinimumSize(QtCore.QSize(324, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.exit_pass_label_2.setFont(font)
        self.exit_pass_label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.exit_pass_label_2.setObjectName("exit_pass_label_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.exit_pass_label_2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setStyleSheet("COLOR:rgb(255, 255, 255)")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 29, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setStyleSheet("background-color: rgba(0, 0, 0, 57);\n"
                                    "                                                        border-radius: 15px;\n"
                                    "                                                        color: rgb(255, 255, 255);\n"
                                    "                                                    ")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setStyleSheet("color: rgba(255, 255, 255, 227);\n"
                                         "                                                        background-color: rgba(0, 0, 0, 140);\n"
                                         "                                                        border-radius: 15px;\n"
                                         "                                                    ")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dest_a.setText(_translate("MainWindow", "A"))
        self.btn_dest_c.setText(_translate("MainWindow", "C"))
        self.btn_dest_b.setText(_translate("MainWindow", "B"))
        self.btn_dest_e.setText(_translate("MainWindow", "E"))
        self.btn_dest_d.setText(_translate("MainWindow", "D"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Contact:"))
        self.label_3.setText(_translate("MainWindow", "Weight(s):"))
        self.btn_dest_a_2.setText(_translate("MainWindow", "+"))
        self.btn_dest_a_3.setText(_translate("MainWindow", "-"))
        self.make_entry_btn.setText(_translate("MainWindow", "ENTRY"))
        self.make_exit_btn.setText(_translate("MainWindow", "EXIT"))
        self.entry_pass_label.setText(_translate("MainWindow", "TextLabel"))
        self.exit_pass_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "TRACKER"))


import res_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
